devscout_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: devscout
      password: devscout_pass
      dbname: devscout_dw
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public,silver,gold
      
    prod:
      type: postgres
      host: postgres
      port: 5432
      user: devscout
      password: devscout_pass
      dbname: devscout_dw
      schema: public
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public,silver,gold
